name: CI
on:
  push:
    branches: [ hasretsariyer-patch-1 ]
  pull_request:
    branches: [ hasretsariyer-patch-1 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Firebase App Distribution
        uses: hasretsariyer/firebase-app-distribution-github-action@v1.0
        with:
          app_id: ${{secrets.FIREBASE_APP_ID}}
          firebase_token: ${{secrets.FIREBASE_TOKEN}}
          app_file: app-release.apk
          tester_groups: maintainers

